#define EEPROM_MODE_OFFSET 0
#define EEPROM_DATA_OFFSET 1

#define EEPROM_SSID_NAME 0
#define EEPROM_SSID_PW 1
#define EEPROM_IRC_SERVER 2
#define EEPROM_IRC_PORT 3
#define EEPROM_IRC_NICK 4
#define EEPROM_IRC_USER 5
#define EEPROM_IRC_FULLNAME 6
